language: python
python:
  - "2.7"

virtualenv:
    system_site_packages: true

# command to install dependencies
before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get -qq update
  - sudo apt-get -qq install python-numpy python-scipy python-opencv
  - sudo apt-get -qq install libhdf5-serial-dev hdf5-tools
  - pip install -r requirements.txt
  - pip install . -e


# command to run tests
script: python ./tests/runner.py
